---
- name: Setup cron service
  cron:
    name: 'ownCloud Background Jobs'
    minute: '{{ owncloud_cron_minute }}'
    user: '{{ owncloud_user }}'
    job: '/usr/bin/php -f {{ owncloud_deploy_path }}/cron.php'
    cron_file: 'owncloud'

- name: Setup logrotate for owncloud
  template:
    src: etc/logrotate.d/owncloud.j2
    dest: /etc/logrotate.d/owncloud
    owner: root
    group: root
    mode: 0644

- name: Get MySQL password
  set_fact:
    owncloud_database_password: '{{ owncloud_database_map[owncloud_database].dbpass }}'

- name: Lookup admin password
  set_fact:
    owncloud_admin_password: "{{ owncloud_admin_password }}"

- name: Check if ownCloud is configured
  stat:
    path: '{{ owncloud_deploy_path }}/config/config.php'
  register: owncloud_config_file

- name: Install ownCloud autoconfig file
  template:
    src: var/www/owncloud/config/autoconfig.php.j2
    dest: '{{ owncloud_deploy_path }}/config/autoconfig.php'
    owner: www-data
    group: www-data
    mode: 0660
  when: owncloud_config_file is defined and not owncloud_config_file.stat.exists

- name: Install ownCloud default config file
  template:
    src: var/www/owncloud/config/config.default.php.j2
    dest: '{{ owncloud_deploy_path }}/config/config.php'
    owner: www-data
    group: www-data
    mode: 0640
  when: owncloud_config_file is defined and not owncloud_config_file.stat.exists

- name: Use cron for background jobs (lib/private/...)
  lineinfile:
    dest: '{{ owncloud_deploy_path }}/settings/admin.php'
    state: present
    regexp: "$template->assign('backgroundjobs_mode', $appConfig->getValue('core', 'backgroundjobs_mode', 'ajax'));"
    line: "$template->assign('backgroundjobs_mode', $appConfig->getValue('core', 'backgroundjobs_mode', 'cron'));"
  when: owncloud_config_file is defined and not owncloud_config_file.stat.exists

- name: Use cron for background jobs (settings/admin.php)
  lineinfile:
     dest: '{{ owncloud_deploy_path }}/settings/admin.php'
     state: present
     regexp: "'backgroundjobs_mode', OC_Appconfig::getValue"
     line: "$tmpl->assign('backgroundjobs_mode', OC_Appconfig::getValue('core', 'backgroundjobs_mode', 'cron'));"
  when: not owncloud_config_file

- name: Flush handlers if automatic setup is requested
  meta: flush_handlers
  when: owncloud_config_file is defined and not owncloud_config_file.stat.exists and
        owncloud_admin_username and owncloud_autosetup

- name: Set previous installed
  tags: previous_database
  lineinfile:
    dest: '{{ owncloud_deploy_path }}/config/config.php'
    state: present
    insertbefore: '^\);'
    line: "  'installed' => true,"
  when: previous_database

- name: Automatically finish setup if allowed
  tags: auto_finish
  uri:
    url: 'https://{{ owncloud_domain[0] }}/index.php'
  when: owncloud_config_file is defined and not owncloud_config_file.stat.exists and
        owncloud_admin_username and owncloud_autosetup and not previous_database
