---

- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - imagemagick
    - libmysqlclient-dev
    - mysql-client-core-5.5
    - curl
    - exim4
    - python-httplib2
