---
- name: Add universe repo
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe' state=present
  when: ansible_distribution == "Ubuntu"

- name: Add ownCloud repo
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_{{ ansible_distribution_version }}/ /' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= 12

- name: Add ownCloud repo key
  apt_key: url='http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_{{ ansible_distribution_version }}/Release.key' state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= 12

- include: install_packages.yml
  handlers:
    - include: 'handlers/main.yml'
  tags: install_owncloud_packages

- include: configure_php.yml
  handlers:
    - include: 'handlers/main.yml'
  tags: configure_owncloud_php   

- include: configure_nginx.yml
  handlers:
    - include: 'handlers/main.yml'
  tags: configure_owncloud_nginx

- name: Install ownCloud
  apt: name=owncloud state=present force=yes
  tags: install_owncloud
- include: configure_owncloud.yml
